### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by LukeGoodsell** [PoisonAlien/varscan_accessories#1]
Hi,

Your vs_format_converter.py script looks very useful, thank you for sharing it. However, because you haven't stated a license for it, it's [not actual legal for anyone to use it](https://choosealicense.com/no-license/).

Please can you add license information to your repo so that I can give your script a try? [This site](https://choosealicense.com/) makes it easy to choose the right one for you.

Thanks,
Luke

**Comment by PoisonAlien** [comment]
Hi,

Glad that you found this script useful and thanks for suggestion. I have put it under MIT license. Thanks again.

**Comment by LukeGoodsell** [comment]
Thanks!

It worked great with some minor tweaking; I'll create a pull request for the changes in case you (or anyone else) finds them useful.
